# Generated by Django 5.0.4 on 2024-04-23 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipts',
            options={'ordering': ['-date']},
        ),
    ]
