# Generated by Django 5.0.4 on 2024-05-13 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Wireman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, null=True, upload_to='electrical/photo/')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('signature', models.FileField(blank=True, null=True, upload_to='electrical/signature/')),
                ('license_no', models.CharField(blank=True, max_length=5, null=True)),
                ('i_date', models.DateField(blank=True, null=True, verbose_name='Issued Date')),
                ('ex_date', models.DateField(blank=True, null=True, verbose_name='Expired Date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('stamp', models.FileField(blank=True, null=True, upload_to='electrical/stamp/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electrical.category')),
            ],
        ),
    ]
