# Generated by Django 5.0.4 on 2024-04-04 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0002_electrical_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='electrical',
            name='date',
        ),
        migrations.RemoveField(
            model_name='electrical',
            name='message',
        ),
        migrations.AddField(
            model_name='electrical',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrical',
            name='ex_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expired Date'),
        ),
        migrations.AddField(
            model_name='electrical',
            name='i_date',
            field=models.DateField(blank=True, null=True, verbose_name='Issued Date'),
        ),
        migrations.AddField(
            model_name='electrical',
            name='license_no',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='electrical',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electrical',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='electrical/photo/'),
        ),
        migrations.AddField(
            model_name='electrical',
            name='signature',
            field=models.FileField(blank=True, null=True, upload_to='electrical/signature/'),
        ),
        migrations.AddField(
            model_name='electrical',
            name='stamp',
            field=models.FileField(blank=True, null=True, upload_to='electrical/stamp/'),
        ),
        migrations.AlterField(
            model_name='electrical',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='electrical',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='electrical.category'),
        ),
    ]
