# Generated by Django 5.0.4 on 2024-04-05 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0003_category_remove_electrical_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
