# Generated by Django 5.0.4 on 2024-04-23 13:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0004_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrical',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='electrical',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
