# Generated by Django 5.0.4 on 2024-05-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0005_electrical_created_at_electrical_updated_at'),
        ('inspections', '0005_alter_inspection_app_name_alter_inspection_app_no_and_more'),
        ('receipts', '0003_remove_receipts_paid_alter_receipts_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Electrical',
            new_name='Wireman',
        ),
    ]
