# Generated by Django 5.0.4 on 2024-05-21 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('licence_no', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='electrical/photo/')),
                ('dob', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('signature', models.FileField(blank=True, null=True, upload_to='electrical/signature/')),
                ('i_date', models.DateField(blank=True, null=True, verbose_name='Issued Date')),
                ('ex_date', models.DateField(blank=True, null=True, verbose_name='Expired Date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('stamp', models.FileField(blank=True, null=True, upload_to='electrical/stamp/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inspections.category')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='inspections.location')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='inspections.post')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('zone', models.CharField(choices=[('north', 'North'), ('central', 'Central'), ('east/west', 'East/West'), ('special', 'Special')], max_length=100)),
                ('vehicle', models.CharField(choices=[('private', 'Private'), ('SLG', 'SLG')], max_length=8)),
                ('start', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('size', models.CharField(max_length=10)),
                ('job_no', models.CharField(max_length=10)),
                ('appl', models.CharField(max_length=5)),
                ('test_data', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('fail', 'Fail'), ('pass', 'Pass')], max_length=4)),
                ('end', models.TimeField()),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='inspections.officer')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='inspections.officer')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('app_no', models.CharField(max_length=5, verbose_name='application number')),
                ('receipt_no', models.CharField(max_length=10, verbose_name='receipt number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cert_no', models.CharField(max_length=10, verbose_name='certificate number')),
                ('name', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('zone', models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], max_length=1, null=True)),
                ('lights', models.IntegerField(blank=True, default=0, null=True)),
                ('sockets', models.IntegerField(blank=True, default=0, null=True)),
                ('switches', models.IntegerField(blank=True, default=0, null=True)),
                ('LE', models.FloatField(blank=True, default=0, null=True)),
                ('LN', models.FloatField(blank=True, default=0, null=True)),
                ('EN', models.FloatField(blank=True, default=0, null=True)),
                ('ins_type', models.CharField(blank=True, choices=[('dom', 'Domestic'), ('com', 'Commercial'), ('temp', 'Temporary'), ('rout', 'Routine')], max_length=15, null=True, verbose_name='inspection type')),
                ('mA', models.IntegerField(blank=True, default=0, null=True)),
                ('sub_circuit', models.IntegerField(blank=True, default=0, null=True)),
                ('main_rating', models.IntegerField(blank=True, default=0, null=True)),
                ('inspection_date', models.DateField()),
                ('collected_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date_collected', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='inspections/applications/')),
                ('assistant', models.ManyToManyField(blank=True, related_name='app_assistants', to='inspections.officer')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='inspections.officer')),
                ('inspector', models.ManyToManyField(blank=True, related_name='app_inspectors', to='inspections.officer')),
            ],
        ),
        migrations.CreateModel(
            name='Defect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_no', models.IntegerField(null=True, unique=True)),
                ('date', models.DateField()),
                ('app_no', models.CharField(max_length=5, verbose_name='application number')),
                ('app_name', models.CharField(max_length=100, verbose_name="applicant's name")),
                ('location', models.CharField(max_length=255)),
                ('insp_date', models.DateField(verbose_name='inspection date')),
                ('defects', models.TextField()),
                ('re_insp_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='re-inspection fee')),
                ('defect_sheet', models.FileField(null=True, upload_to='inspections/defect_sheet/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiremen', to='inspections.officer', verbose_name='wireman/contactor')),
            ],
        ),
    ]
