# Generated by Django 5.0.4 on 2024-04-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='sheet_no',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
