# Generated by Django 5.0.4 on 2024-05-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_alter_inspector_office'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspector',
            name='log_sheet',
        ),
        migrations.AlterField(
            model_name='inspector',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
