# Generated by Django 5.0.4 on 2024-04-23 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_sheet_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspection',
            old_name='description',
            new_name='defects',
        ),
    ]
