# Generated by Django 5.0.4 on 2024-05-15 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electrical', '0001_initial'),
        ('inspections', '0003_remove_inspector_log_sheet_alter_inspector_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='inspector',
        ),
        migrations.AddField(
            model_name='defect',
            name='wireman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wiremen', to='electrical.wireman', verbose_name='wireman/contactor'),
        ),
    ]
