# Generated by Django 5.0.4 on 2024-05-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_remove_defect_inspector_defect_wireman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='zone',
            field=models.CharField(choices=[('north', 'North'), ('central', 'Central'), ('east/west', 'East/West')], max_length=100),
        ),
    ]
