# Generated by Django 5.0.4 on 2024-04-23 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0004_inspection_defect_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='app_name',
            field=models.CharField(max_length=100, verbose_name="applicant's name"),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='app_no',
            field=models.CharField(max_length=5, verbose_name='application number'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='insp_date',
            field=models.DateField(verbose_name='inspection date'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='re_insp_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='re-inspection fee'),
        ),
    ]
