# Generated by Django 5.0.4 on 2024-05-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0006_inspectiondailylog_delete_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('app_no', models.CharField(max_length=5, verbose_name='application number')),
                ('receipt_no', models.CharField(max_length=10, verbose_name='receipt number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cert_no', models.CharField(max_length=10, verbose_name='certificate number')),
                ('area', models.CharField(max_length=100)),
                ('ins_type', models.CharField(choices=[('new', 'New'), ('alteration', 'Alteration'), ('extension', 'Extension'), ('reconnection', 'Reconnection')], max_length=15, verbose_name='inspection type')),
                ('applicant', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('owner_address', models.TextField()),
                ('install_location', models.TextField()),
                ('nature_of_work', models.CharField(choices=[('domestic', 'Domestic'), ('commercial', 'Commercial'), ('temporary', 'Temporary'), ('routine', 'Routine')], max_length=20)),
                ('points', models.IntegerField()),
                ('contactor', models.CharField(max_length=100)),
                ('contactor_address', models.TextField()),
                ('contactor_licence_no', models.CharField(max_length=100, verbose_name='licence number')),
                ('file', models.FileField(blank=True, null=True, upload_to='inspections/applications/')),
                ('lights', models.IntegerField(default=0)),
                ('sockets', models.IntegerField(default=0)),
                ('switches', models.IntegerField(default=0)),
                ('bc', models.IntegerField(default=0)),
                ('le', models.FloatField(default=0)),
                ('ln', models.FloatField(default=0)),
                ('en', models.FloatField(default=0)),
                ('ea', models.FloatField(default=0)),
                ('mA', models.FloatField(default=0)),
                ('sub_circuit', models.IntegerField(default=0)),
                ('main_rating', models.IntegerField(default=0)),
                ('collected_by', models.CharField(max_length=100)),
                ('date_collected', models.DateField()),
                ('assistant', models.ManyToManyField(related_name='app_assistants', to='inspections.inspector')),
                ('inspector', models.ManyToManyField(related_name='app_inspectors', to='inspections.inspector')),
            ],
        ),
    ]
