# Generated by Django 5.0.4 on 2024-05-15 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0007_inspectionapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionapplication',
            old_name='install_location',
            new_name='location',
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='ins_type',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('alteration', 'Alteration'), ('extension', 'Extension'), ('reconnection', 'Reconnection')], max_length=15, null=True, verbose_name='inspection type'),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='owner_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
