# Generated by Django 5.0.4 on 2024-05-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0008_rename_install_location_inspectionapplication_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionapplication',
            name='owner_address',
            field=models.TextField(blank=True, null=True, verbose_name="owner's address"),
        ),
    ]
