# Generated by Django 5.0.4 on 2024-05-15 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0009_alter_inspectionapplication_owner_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionapplication',
            old_name='applicant',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='inspectionapplication',
            name='contactor_address',
        ),
        migrations.RemoveField(
            model_name='inspectionapplication',
            name='contactor_licence_no',
        ),
        migrations.RemoveField(
            model_name='inspectionapplication',
            name='location',
        ),
        migrations.RemoveField(
            model_name='inspectionapplication',
            name='nature_of_work',
        ),
        migrations.RemoveField(
            model_name='inspectionapplication',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='inspectionapplication',
            name='owner_address',
        ),
        migrations.RemoveField(
            model_name='inspectionapplication',
            name='points',
        ),
        migrations.AddField(
            model_name='inspectionapplication',
            name='inspection_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectionapplication',
            name='zone',
            field=models.CharField(blank=True, choices=[('1', 'One'), ('2', 'Two'), ('3', 'Three')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='date_collected',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='ins_type',
            field=models.CharField(blank=True, choices=[('domestic', 'Domestic'), ('commercial', 'Commercial'), ('temporary', 'Temporary'), ('routine', 'Routine')], max_length=15, null=True, verbose_name='inspection type'),
        ),
    ]
