# Generated by Django 5.0.4 on 2024-05-15 18:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0010_rename_applicant_inspectionapplication_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectionapplication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inspectionapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
