# Generated by Django 5.0.4 on 2024-05-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0011_inspectionapplication_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionapplication',
            old_name='bc',
            new_name='BC',
        ),
    ]
