# Generated by Django 5.0.4 on 2024-05-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0014_alter_inspectionapplication_ins_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionapplication',
            name='mA',
            field=models.IntegerField(default=0),
        ),
    ]
