# Generated by Django 5.0.4 on 2024-05-15 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0016_inspector_licence_no_alter_inspector_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='inspections.post'),
        ),
    ]
