# Generated by Django 5.0.4 on 2024-05-15 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0017_alter_inspector_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionapplication',
            name='contactor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='inspections.inspector'),
        ),
    ]
