# Generated by Django 5.0.4 on 2024-05-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0018_alter_inspectionapplication_contactor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionapplication',
            name='AE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='BC',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='EN',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='LE',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='LN',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='collected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='lights',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='mA',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='main_rating',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='sockets',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='sub_circuit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='switches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
