# Generated by Django 5.0.4 on 2024-05-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0020_rename_contactor_inspectionapplication_contractor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionapplication',
            name='assistant',
            field=models.ManyToManyField(blank=True, related_name='app_assistants', to='inspections.inspector'),
        ),
        migrations.AlterField(
            model_name='inspectionapplication',
            name='inspector',
            field=models.ManyToManyField(blank=True, related_name='app_inspectors', to='inspections.inspector'),
        ),
    ]
