# Generated by Django 5.0.4 on 2024-05-17 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0021_alter_inspectionapplication_assistant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspectionapplication',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
