# Generated by Django 5.0.4 on 2024-05-17 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0022_alter_inspectionapplication_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspectionapplication',
            name='AE',
        ),
        migrations.RemoveField(
            model_name='inspectionapplication',
            name='BC',
        ),
    ]
